# Generated by Django 5.1.4 on 2025-02-07 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('Vegetal', 'Vegetal'), ('Carne', 'Carne'), ('Grano', 'Grano')], max_length=50)),
                ('cantidad', models.PositiveIntegerField()),
                ('caducidad', models.DateField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
